// Generated by gencpp from file hexapodservice/hexapodserviceResult.msg
// DO NOT EDIT!


#ifndef HEXAPODSERVICE_MESSAGE_HEXAPODSERVICERESULT_H
#define HEXAPODSERVICE_MESSAGE_HEXAPODSERVICERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hexapodservice
{
template <class ContainerAllocator>
struct hexapodserviceResult_
{
  typedef hexapodserviceResult_<ContainerAllocator> Type;

  hexapodserviceResult_()
    : status(0)
    , freespace(0)
    , motionActive(false)
    , result()  {
    }
  hexapodserviceResult_(const ContainerAllocator& _alloc)
    : status(0)
    , freespace(0)
    , motionActive(false)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef int32_t _freespace_type;
  _freespace_type freespace;

   typedef uint8_t _motionActive_type;
  _motionActive_type motionActive;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> const> ConstPtr;

}; // struct hexapodserviceResult_

typedef ::hexapodservice::hexapodserviceResult_<std::allocator<void> > hexapodserviceResult;

typedef boost::shared_ptr< ::hexapodservice::hexapodserviceResult > hexapodserviceResultPtr;
typedef boost::shared_ptr< ::hexapodservice::hexapodserviceResult const> hexapodserviceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapodservice::hexapodserviceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hexapodservice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hexapodservice': ['/home/quan/hexapod_service_ws/src/hexapodservice/msg', '/home/quan/hexapod_service_ws/devel/share/hexapodservice/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84ae386391a6712ba3f1d0cdfd23bad0";
  }

  static const char* value(const ::hexapodservice::hexapodserviceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84ae386391a6712bULL;
  static const uint64_t static_value2 = 0xa3f1d0cdfd23bad0ULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapodservice/hexapodserviceResult";
  }

  static const char* value(const ::hexapodservice::hexapodserviceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 status\n\
int32 freespace\n\
bool motionActive\n\
string result\n\
";
  }

  static const char* value(const ::hexapodservice::hexapodserviceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.freespace);
      stream.next(m.motionActive);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hexapodserviceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapodservice::hexapodserviceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapodservice::hexapodserviceResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "freespace: ";
    Printer<int32_t>::stream(s, indent + "  ", v.freespace);
    s << indent << "motionActive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motionActive);
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPODSERVICE_MESSAGE_HEXAPODSERVICERESULT_H
