// Generated by gencpp from file hexapodservice/hexapodserviceFeedback.msg
// DO NOT EDIT!


#ifndef HEXAPODSERVICE_MESSAGE_HEXAPODSERVICEFEEDBACK_H
#define HEXAPODSERVICE_MESSAGE_HEXAPODSERVICEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hexapodservice/leg.h>

namespace hexapodservice
{
template <class ContainerAllocator>
struct hexapodserviceFeedback_
{
  typedef hexapodserviceFeedback_<ContainerAllocator> Type;

  hexapodserviceFeedback_()
    : ALLLEGS_fdbk()  {
    }
  hexapodserviceFeedback_(const ContainerAllocator& _alloc)
    : ALLLEGS_fdbk(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hexapodservice::leg_<ContainerAllocator>  _ALLLEGS_fdbk_type;
  _ALLLEGS_fdbk_type ALLLEGS_fdbk;




  typedef boost::shared_ptr< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct hexapodserviceFeedback_

typedef ::hexapodservice::hexapodserviceFeedback_<std::allocator<void> > hexapodserviceFeedback;

typedef boost::shared_ptr< ::hexapodservice::hexapodserviceFeedback > hexapodserviceFeedbackPtr;
typedef boost::shared_ptr< ::hexapodservice::hexapodserviceFeedback const> hexapodserviceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hexapodservice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hexapodservice': ['/home/quan/hexapod_service_ws/src/hexapodservice/msg', '/home/quan/hexapod_service_ws/devel/share/hexapodservice/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "403f7a6b04ba80a9669cf3a75e8e9e8d";
  }

  static const char* value(const ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x403f7a6b04ba80a9ULL;
  static const uint64_t static_value2 = 0x669cf3a75e8e9e8dULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapodservice/hexapodserviceFeedback";
  }

  static const char* value(const ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
hexapodservice/leg ALLLEGS_fdbk\n\
\n\
\n\
================================================================================\n\
MSG: hexapodservice/leg\n\
hexapodservice/legjoint[6] leg\n\
\n\
================================================================================\n\
MSG: hexapodservice/legjoint\n\
float64 coxa\n\
float64 femur\n\
float64 tibia\n\
float64 tarsus\n\
";
  }

  static const char* value(const ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ALLLEGS_fdbk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hexapodserviceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapodservice::hexapodserviceFeedback_<ContainerAllocator>& v)
  {
    s << indent << "ALLLEGS_fdbk: ";
    s << std::endl;
    Printer< ::hexapodservice::leg_<ContainerAllocator> >::stream(s, indent + "  ", v.ALLLEGS_fdbk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPODSERVICE_MESSAGE_HEXAPODSERVICEFEEDBACK_H
