// Generated by gencpp from file hexapodservice/legjoints.msg
// DO NOT EDIT!


#ifndef HEXAPODSERVICE_MESSAGE_LEGJOINTS_H
#define HEXAPODSERVICE_MESSAGE_LEGJOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hexapodservice
{
template <class ContainerAllocator>
struct legjoints_
{
  typedef legjoints_<ContainerAllocator> Type;

  legjoints_()
    : coxa()
    , femur()
    , tibia()
    , tarsus()  {
    }
  legjoints_(const ContainerAllocator& _alloc)
    : coxa(_alloc)
    , femur(_alloc)
    , tibia(_alloc)
    , tarsus(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _coxa_type;
  _coxa_type coxa;

   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _femur_type;
  _femur_type femur;

   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _tibia_type;
  _tibia_type tibia;

   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _tarsus_type;
  _tarsus_type tarsus;




  typedef boost::shared_ptr< ::hexapodservice::legjoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapodservice::legjoints_<ContainerAllocator> const> ConstPtr;

}; // struct legjoints_

typedef ::hexapodservice::legjoints_<std::allocator<void> > legjoints;

typedef boost::shared_ptr< ::hexapodservice::legjoints > legjointsPtr;
typedef boost::shared_ptr< ::hexapodservice::legjoints const> legjointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapodservice::legjoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapodservice::legjoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hexapodservice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hexapodservice': ['/home/quan/hexapod_service_ws/src/hexapodservice/msg', '/home/quan/hexapod_service_ws/devel/share/hexapodservice/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::legjoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::legjoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::legjoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::legjoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::legjoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::legjoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapodservice::legjoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30491f146cc62d519f29e03cbd6340f7";
  }

  static const char* value(const ::hexapodservice::legjoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30491f146cc62d51ULL;
  static const uint64_t static_value2 = 0x9f29e03cbd6340f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapodservice::legjoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapodservice/legjoints";
  }

  static const char* value(const ::hexapodservice::legjoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapodservice::legjoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] coxa\n\
int64[] femur\n\
int64[] tibia\n\
int64[] tarsus\n\
";
  }

  static const char* value(const ::hexapodservice::legjoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapodservice::legjoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coxa);
      stream.next(m.femur);
      stream.next(m.tibia);
      stream.next(m.tarsus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct legjoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapodservice::legjoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapodservice::legjoints_<ContainerAllocator>& v)
  {
    s << indent << "coxa[]" << std::endl;
    for (size_t i = 0; i < v.coxa.size(); ++i)
    {
      s << indent << "  coxa[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.coxa[i]);
    }
    s << indent << "femur[]" << std::endl;
    for (size_t i = 0; i < v.femur.size(); ++i)
    {
      s << indent << "  femur[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.femur[i]);
    }
    s << indent << "tibia[]" << std::endl;
    for (size_t i = 0; i < v.tibia.size(); ++i)
    {
      s << indent << "  tibia[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.tibia[i]);
    }
    s << indent << "tarsus[]" << std::endl;
    for (size_t i = 0; i < v.tarsus.size(); ++i)
    {
      s << indent << "  tarsus[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.tarsus[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPODSERVICE_MESSAGE_LEGJOINTS_H
